/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anchal
 */
public class Addpostpanel extends javax.swing.JPanel {

    /**
     * Creates new form Addpostpanel
     */
    public Addpostpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jcaption = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jaddstory = new javax.swing.JButton();
        jphoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(null);

        jcaption.setColumns(20);
        jcaption.setRows(5);
        jScrollPane1.setViewportView(jcaption);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 120, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(250, 20, 130, 30);

        jaddstory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jaddstory.setText("ADD STORY");
        jaddstory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddstoryActionPerformed(evt);
            }
        });
        add(jaddstory);
        jaddstory.setBounds(250, 70, 130, 30);

        jphoto.setText("jLabel1");
        add(jphoto);
        jphoto.setBounds(10, 10, 190, 90);
    }// </editor-fold>//GEN-END:initComponents

    private void jaddstoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddstoryActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jaddstoryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jaddstory;
    public javax.swing.JTextArea jcaption;
    public javax.swing.JLabel jphoto;
    // End of variables declaration//GEN-END:variables
}
