
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Anchal
 */
public class Addstory extends javax.swing.JFrame {

    /**
     * Creates new form Addstory
     */
    File f;
    int postid;

    public Addstory(int postid) {
        initComponents();
        this.postid = postid;
        setSize(2000, 2000);
        setVisible(true);
        showStories();

    }

    void showStories() {
        //send unirest get requyest on a resource getAllPosts
        //with username
//        recieve response
        try {
            HttpResponse<String> res = Unirest.get("http://localhost:8999/getAllstories")
                    .queryString("postid", postid)
                    .asString();
            if (res.getStatus() == 200) //server working correctly
            {
                String response = res.getBody();
                System.out.println("Response is ----->" + response);
                if (response.equals("success")) {
                    JOptionPane.showMessageDialog(this, "added Successfull");

                } else {
                    System.out.println("Respnse is" + response);
                    StringTokenizer st = new StringTokenizer(response, "~~");
                    int count = st.countTokens();
                    MainPanel.setPreferredSize(new Dimension(800, count * 250));
                    Addstorypanel obj[] = new Addstorypanel[count];
                    int x = 10, y = 10;
                    MainPanel.removeAll();
                    for (int i = 0; i < count; i++) {
                        String userinfo = st.nextToken();
                        StringTokenizer st2 = new StringTokenizer(userinfo, "!!");
                        String caption = st2.nextToken();
                        String photo = st2.nextToken();
                        int storyid = Integer.parseInt(st2.nextToken());

                        System.out.println("caption--------" + caption);
                        System.out.println("Photo------------" + photo);
                        obj[i] = new Addstorypanel();
                        obj[i].jcaption.setText(caption);
                        obj[i].jphoto.setText(photo);
                        try {
                            URL url = new URL(global.ip_address + "GetResource/" + photo);
                            //System.out.println("Path of Image Stored in server side--------------" + url);
                            BufferedImage img = ImageIO.read(url);
                            Image resizedimage = img.getScaledInstance(obj[i].jphoto.getWidth(), obj[i].jphoto.getHeight(), Image.SCALE_SMOOTH);
                            obj[i].jphoto.setIcon(new ImageIcon(resizedimage));

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        

                        obj[i].setBounds(x, y, 700, 200);
                        MainPanel.add(obj[i]);
                        y += 230;
                    }
                    MainPanel.repaint();  //refresh
                    repaint();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jcaption = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jphoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADD STORY HERE!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 180, 53);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Caption");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 100, 40);

        jcaption.setColumns(20);
        jcaption.setRows(5);
        jScrollPane1.setViewportView(jcaption);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 90, 166, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Photo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 240, 60, 30);

        jphoto.setText("photo");
        getContentPane().add(jphoto);
        jphoto.setBounds(170, 220, 160, 80);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 360, 100, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("ADD STORY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 460, 180, 70);

        MainPanel.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(MainPanel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(352, 12, 430, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String caption = jcaption.getText();
//        String photo=jphoto.getText();
        if (caption.equals("")) {
            JOptionPane.showMessageDialog(this, "All fields are required");
        } else if (f == null) {
            JOptionPane.showMessageDialog(this, "All fields are required");
        } else {
            try {
                HttpResponse<String> res = Unirest.post("http://localhost:8999/useraddstory")
                        .queryString("postid", postid)
                        .queryString("caption", caption)
                        .field("photo", f)
                        .asString();
                if (res.getStatus() == 200) //server working correctly
                {
                    String response = res.getBody();
                    System.out.println("Response is ----->" + response);
                    if (response.equals("success")) {
                        JOptionPane.showMessageDialog(this, "story added Successfull");

                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to add story");
                    }

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int ans = chooser.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.getPath());
            Image resizedImage = icon.getImage().getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
            jphoto.setIcon(new ImageIcon(resizedImage));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addstory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addstory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addstory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addstory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addstory(4).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jcaption;
    private javax.swing.JLabel jphoto;
    // End of variables declaration//GEN-END:variables
}
