/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anchal
 */
public class Addstorypanel extends javax.swing.JPanel {

    /**
     * Creates new form Addstorypanel
     */
    public Addstorypanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jphoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jcaption = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setLayout(null);

        jphoto.setText("jLabel1");
        add(jphoto);
        jphoto.setBounds(20, 20, 110, 70);

        jcaption.setColumns(20);
        jcaption.setRows(5);
        jScrollPane1.setViewportView(jcaption);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 100, 166, 71);

        jButton3.setText("Delete");
        add(jButton3);
        jButton3.setBounds(230, 40, 110, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jcaption;
    public javax.swing.JLabel jphoto;
    // End of variables declaration//GEN-END:variables
}
