
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anchal
 */
public class forgot_password extends javax.swing.JFrame {

    /**
     * Creates new form forgot_password
     */
    String username;
    String otp;
    
    public forgot_password() {
        initComponents();
        
        jPanel1.setBounds(40,100,420,130);
        jPanel2.setBounds(40,100,420,130);
        jPanel3.setBounds(40,100,420,300);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        setSize(500,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jotp = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jnewpassword = new javax.swing.JTextField();
        jconfirmpassword = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORGOT PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 20, 200, 35);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(146, 12, 220, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Useranme");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 50, 90, 30);
        jPanel1.add(jusername);
        jusername.setBounds(230, 50, 140, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("Generate OTP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(151, 91, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 70, 530, 140);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("OTP Verification");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(150, 10, 186, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Enter OTP");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(11, 50, 120, 20);
        jPanel2.add(jotp);
        jotp.setBounds(230, 50, 150, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(140, 101, 110, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 240, 530, 140);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Set New Password");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(160, 0, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("New Password");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 60, 80, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Confirm Password");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 100, 90, 30);
        jPanel3.add(jnewpassword);
        jnewpassword.setBounds(190, 50, 120, 30);
        jPanel3.add(jconfirmpassword);
        jconfirmpassword.setBounds(190, 99, 120, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(120, 141, 120, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 410, 550, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        username=jusername.getText();
        if(username.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please Enter a username");
        }
        else{
            try{
                HttpResponse<String> res=Unirest.get("http://localhost:8999/userforgotpassword")
                        .queryString("username",username)
                        .asString();
                 if (res.getStatus() == 200) {
                    
                    String ans = res.getBody();
                    if (ans.equals("fails"))
                    {
                        JOptionPane.showMessageDialog(this, "NO user found with thids username");
                    }
                    else{
                        otp=ans;
                        JOptionPane.showMessageDialog(this, "otp is"+ans);
                        jPanel1.setVisible(false);
                        jPanel2.setVisible(true);
                    }
                    
                }
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String otp1=jotp.getText();
         if(username.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please Enter an otp");
        }else{
             if(otp1.equals(otp)){
                 jPanel2.setVisible(false);
                 jPanel3.setVisible(true);
                 
             }
             else{
                 JOptionPane.showMessageDialog(this,"Please Enter correct otp");
                 
             }
         }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String newpassword=jnewpassword.getText();
        String cpassword=jconfirmpassword.getText();
        if(newpassword.isEmpty()||cpassword.isEmpty()){
            
        
        
            JOptionPane.showMessageDialog(this,"Fill all the details");
        }else if (!(newpassword.equals(cpassword))) {
            JOptionPane.showMessageDialog(this, "Password and ConfirmPassword should be same");}
        else{
            try{
                HttpResponse<String> res=Unirest.get("http://localhost:8999/usersetpassword")
                        .queryString("username",username)
                        .queryString("newpassword",newpassword)
                        .asString();
                if (res.getStatus() == 200) {
                    
                    String ans = res.getBody();
                    JOptionPane.showMessageDialog(this,ans);
                    if(ans.equals("updated")){
                        JOptionPane.showMessageDialog(this,"Password updated succesfully");
                        dispose();
                        UserLoginFrame obj=new UserLoginFrame();} 
                    else{
                        JOptionPane.showMessageDialog(this,"Something went wrong");
                    }
                    
                        
                    }
                       
                
            }
            catch(Exception ex){
                ex.printStackTrace();
            }
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jconfirmpassword;
    private javax.swing.JTextField jnewpassword;
    private javax.swing.JTextField jotp;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables
}
