/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anchal
 */
public class myfollowerspaneldesign extends javax.swing.JPanel {

    /**
     * Creates new form myfollowerspaneldesign
     */
    public myfollowerspaneldesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jusername = new javax.swing.JLabel();
        jphoto = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Remove followers");
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 20, 190, 60);

        jusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jusername.setText("username");
        jPanel1.add(jusername);
        jusername.setBounds(10, 20, 130, 50);

        jphoto.setText("photo");
        jPanel1.add(jphoto);
        jphoto.setBounds(10, 80, 140, 80);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
        jScrollPane1.setBounds(22, 22, 450, 200);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jphoto;
    public javax.swing.JLabel jusername;
    // End of variables declaration//GEN-END:variables
}
