
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Anchal
 * 
 *  */
public class MyFollowers extends javax.swing.JFrame {

    /**
     * Creates new form MyFollowers
     */
    String username;
    String photo = "";

    public MyFollowers(String n) {
        username = n;
        initComponents();
        getfollower();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void getfollower() {
        try {
            HttpResponse<String> res = Unirest.get("http://localhost:8999/myfollower")
                    .queryString("username", username)
                    .asString();
            if (res.getStatus() == 200) {
                String ans = res.getBody();
                if (ans.equals("fails")) {
                    JOptionPane.showMessageDialog(rootPane, "No follower");

                } else {
                    System.out.println("Respnse is" + ans);

                    StringTokenizer st = new StringTokenizer(ans, "&&");
                    int count = st.countTokens();
                    mainPanel.setPreferredSize(new Dimension(800, count * 250));
                    myfollowerspaneldesign obj[] = new myfollowerspaneldesign[count];
                    int x = 10, y = 10;
                    mainPanel.removeAll();
                    for (int i = 0; i < count; i++) {
                        String userinfo = st.nextToken();
                        StringTokenizer st2 = new StringTokenizer(userinfo, ";;");
                        String user = st2.nextToken();
                        String photo = st2.nextToken();
                        String followerid = st2.nextToken();
                        System.out.println("username--------" + username);
                        System.out.println("Photo------------" + photo);
                        obj[i] = new myfollowerspaneldesign();

                        obj[i].jButton1.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                try {
                                    HttpResponse<String> res = Unirest.get("http://localhost:8999/deletefollower")
                                            .queryString("followerid", followerid)
                                            .asString();
                                    if (res.getStatus() == 200) {
                                        String ans = res.getBody();
                                        if (ans.equals("success")) {
                                           getfollower();
                                                   

                                            //To change body of generated methods, choose Tools | Templates.
                                            //send unirest request
                                        }
                                    }
                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                }
                            }

                        });
                        obj[i].jusername.setText(user);
                        obj[i].jphoto.setText(photo);
                        obj[i].setBounds(x, y, 700, 300);
                        mainPanel.add(obj[i]);
                        y += 230;
                    }
                    mainPanel.repaint();  //refresh
                    repaint();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainPanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 690, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFollowers.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFollowers.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFollowers.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFollowers.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MyFollowers("").setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
