/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anchal
 */
public class myfollowingpaneldesign extends javax.swing.JPanel {

    /**
     * Creates new form myfollowingpaneldesign
     */
    public myfollowingpaneldesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jremove = new javax.swing.JButton();
        jusername = new javax.swing.JLabel();
        jphoto = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jremove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jremove.setText("Remove");
        jPanel1.add(jremove);
        jremove.setBounds(260, 20, 130, 60);

        jusername.setBackground(new java.awt.Color(255, 255, 255));
        jusername.setText("username");
        jPanel1.add(jusername);
        jusername.setBounds(10, 20, 130, 40);

        jphoto.setText("photo");
        jPanel1.add(jphoto);
        jphoto.setBounds(10, 80, 190, 100);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
        jScrollPane1.setBounds(42, 30, 430, 200);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jphoto;
    public javax.swing.JButton jremove;
    public javax.swing.JLabel jusername;
    // End of variables declaration//GEN-END:variables
}
